label: Primary (header)
preview: '@uswds-header'
status: 'wip'

context:
  nav:
    search: false
    links:
      - text: Explore benefits
        id: nav-section-one
        links:
          - text: Disability
            id: subnav-one
            links:
              - text: Disability benefits overview
                href: '#'
              - text: Eligibility
                href: '#'
              - text: Application process
                href: '#'
              - text: Conditions
                href: '#'
              - text: Check claim and appeal status
                href: '#'
              - text: Appeals process
                href: '#'
              - text: Go to eBenefits to apply (button)
                href: '#'
          - text: Healthcare
            id:
            links:
              - text: Health care benefits overview
                href: '#'
              - text: Eligibility
                href: '#'
              - text: Application process
                href: '#'
              - text: Health needs and conditions
                href: '#'
              - text: Refill prescriptions
                href: '#'
              - text: Message your healthcare team
                href: '#'
              - text: Apply now (button)
                href: '#'
          - text: Education &amp; training
            id:
            links:
              - text: Education benefits overview
                href: '#'
              - text: Eligibility
                href: '#'
              - text: Application process
                href: '#'
              - text: GI Bill programs
                href: '#'
              - text: Compare GI Bill benefits
                href: '#'
              - text: Go to eBenefits to apply (button)
                href: '#'
          - text: Housing assistance
            id:
            links:
              - text: Housing assistance overview
                href: '#'
              - text: Home loans
                href: '#'
              - text: Adaptive housing grants
                href: '#'
          - text: Careers &amp; employment
            id:
            links:
              - text: Careers &amp; employment overview
                href: '#'
              - text: Find a job/Hire a Veteran
                href: '#'
              - text: Start or grow your business
                href: '#'
              - text: Resources for military &amp; Veteran family members
                href: '#'
          - text: Life insurance
            id:
            links:
              - text: Life insurance overview
                href: '#'
              - text: Options &amp; eligibility
                href: '#'
              - text: Disabled &amp; terminally ill policyholders
                href: '#'
              - text: Managing your policy
                href: '#'
          - text: Pension
            id:
            links:
              - text: Pension benefits overview
                href: '#'
              - text: Eligibility
                href: '#'
              - text: Application process
                href: '#'
              - text: Survivors pension
                href: '#'
              - text: Apply now (button)
                href: '#'
          - text: Burials &amp; memorials
            id:
            links:
              - text: Burials &amp; memorials overview
                href: '#'
              - text: Eligibility
                href: '#'
              - text: Burial planning
                href: '#'
              - text: Survivor &amp; dependent benefits
                href: '#'
      - text: Manage your health &amp; benefits
        id: nav-section-two
        links:
          - text: Refill prescriptions
            href: '#'
          - text: Message your health care team
            href: '#'
          - text: Get your VA health records
            href: '#'
          - text: Check claim and appeal status
            href: '#'
          - text: Check Post-9/11 GI Bill benefits
            href: '#'
      - text: Find VA locations
        href: 'javascript:void(0)'
